version: "3"

networks:
  kafka_network:
    driver: bridge

services:
  source-mysql:
    image: debezium/connect:2.5
    container_name: source-mysql-connector
    platform: linux/arm64
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: 172.31.0.4:9092,172.31.0.5:9093
      GROUP_ID: mysql-source-connector"
      
      CONFIG_STORAGE_TOPIC: mysql-source-config
      OFFSET_STORAGE_TOPIC: mysql-source-offsets
      STATUS_STORAGE_TOPIC: mysql-source-status

      ## equals brocker count
      CONFIG_STORAGE_REPLICATION_FACTOR: "2"
      OFFSET_STORAGE_REPLICATION_FACTOR: "2"
      STATUS_STORAGE_REPLICATION_FACTOR: "2"

      # Converter 설정
      KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"

      KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"

      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: test_user
      MYSQL_PASSWORD: 12341234
      MYSQL_SERVER_ID: 1
    volumes:
      - ../configs/debizium/source.json:/etc/debezium/connect-distributed.properties

    networks:
        - kafka_network


  
